### ISSUE TITLE
Requirements file

### ISSUE THREAD

**Issue by cvoelcker** [facebookresearch/svg#5]
Hi, can you add a quick requirements.txt file to the repo for easier setup? Thanks!

**Comment by bamos** [comment]
Sorry for the delays here. When I started trying to put in a requirements file, I realized that the code isn't compatible with the latest/public version of Mujoco/gym. I just pushed in an update to fix this along with a requirements.txt that should be able to run all of the MBPO environments. The poplin/MBBL envs still depend on an older version of gym and I've not tested them again, something still may need to be updated for those. Please let me know if you have any other issues running the code!

**Comment by bamos** [comment]
Sorry for the delays here. When I started trying to put in a requirements file, I realized that the code isn't compatible with the latest/public version of Mujoco/gym. I just pushed in an update to fix this along with a requirements.txt that should be able to run all of the MBPO environments. The poplin/MBBL envs still depend on an older version of gym and I've not tested them again, something still may need to be updated for those. Please let me know if you have any other issues running the code!
